[Icon Theme]
Name=NewBe
Comment=Modern dimensional icon theme for the NewBe desktop
Inherits=Adwaita,hicolor
Example=folder
Directories=scalable/apps,scalable/actions,scalable/categories,scalable/devices,scalable/emblems,scalable/mimetypes,scalable/places,scalable/status,symbolic/actions,symbolic/apps,symbolic/categories,symbolic/devices,symbolic/places,symbolic/status

[scalable/apps]
Size=48
Type=Scalable
MinSize=16
MaxSize=512
Context=Applications

[scalable/actions]
Size=24
Type=Scalable
MinSize=16
MaxSize=256
Context=Actions

[scalable/categories]
Size=48
Type=Scalable
MinSize=16
MaxSize=512
Context=Categories

[scalable/devices]
Size=48
Type=Scalable
MinSize=16
MaxSize=512
Context=Devices

[scalable/emblems]
Size=48
Type=Scalable
MinSize=16
MaxSize=512
Context=Emblems

[scalable/mimetypes]
Size=48
Type=Scalable
MinSize=16
MaxSize=512
Context=MimeTypes

[scalable/places]
Size=48
Type=Scalable
MinSize=16
MaxSize=512
Context=Places

[scalable/status]
Size=24
Type=Scalable
MinSize=16
MaxSize=256
Context=Status

[symbolic/actions]
Size=16
Type=Scalable
MinSize=16
MaxSize=64
Context=Actions

[symbolic/apps]
Size=16
Type=Scalable
MinSize=16
MaxSize=64
Context=Applications

[symbolic/categories]
Size=16
Type=Scalable
MinSize=16
MaxSize=64
Context=Categories

[symbolic/devices]
Size=16
Type=Scalable
MinSize=16
MaxSize=64
Context=Devices

[symbolic/places]
Size=16
Type=Scalable
MinSize=16
MaxSize=64
Context=Places

[symbolic/status]
Size=16
Type=Scalable
MinSize=16
MaxSize=64
Context=Status
