# alias=compiled cursor target
default=left_ptr
arrow=left_ptr
top_left_arrow=left_ptr
left-arrow=left_ptr
pointer=hand2
hand1=hand2
link=hand2
9d800788f1b08800ae810202380a0822=hand2
xterm=text
ibeam=text
08e8e1c95fe2fc01f976f1e063a24ccd=text
cross=crosshair
tcross=crosshair
diamond_cross=crosshair
cross_reverse=crosshair
watch=wait
left_ptr_watch=progress
3ecb610c1bf2410f44200f48c40d3599=progress
fleur=move
all-scroll=move
4498f0e0c1937ffe01fd06f973665830=move
9081237383d90e509aa00f00170e968f=move
sb_h_double_arrow=ew-resize
h_double_arrow=ew-resize
size_hor=ew-resize
col-resize=ew-resize
028006030e0e7ebffc7f7070c0600140=ew-resize
sb_v_double_arrow=ns-resize
v_double_arrow=ns-resize
size_ver=ns-resize
row-resize=ns-resize
00008160000006810000408080010102=ns-resize
size_bdiag=nesw-resize
fd_double_arrow=nesw-resize
bottom_left_corner=nesw-resize
top_right_corner=nesw-resize
c7088f0f3e6c8088236ef8e1e3e70000=nesw-resize
size_fdiag=nwse-resize
bd_double_arrow=nwse-resize
bottom_right_corner=nwse-resize
top_left_corner=nwse-resize
fcf1c3c7cd4491d801f1e1c78f100000=nwse-resize
forbidden=not-allowed
no-drop=not-allowed
dnd-no-drop=not-allowed
circle=not-allowed
crossed_circle=not-allowed
03b6e0fcb3499374a867c041f52298f0=not-allowed
question_arrow=help
openhand=grab
5aca4d189052212118709018842178c0=grab
closedhand=grabbing
208530c400c041818281048008011002=grabbing
